public class InvoiceUtilities {
 
    // class method to renumber Line Items for a given Invoice number
    // returns a string that indicates success or failure
    public static String renumberLineItems(String invoiceName) {
 
    // create a copy of the target Invoice object and it's Line Items
 
    // loop through each Line Item, renumbering as you go
 
    // update the Line Items in one transaction, rollback if any problems
    // and return error messages to the calling environment
 
    // on success, return the list to the calling program
  }
}
